/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as MypeOnboardingRouteImport } from './routes/mype-onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreelancerOnboardingRouteImport } from './routes/freelancer-onboarding'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentFreelancerIdRouteImport } from './routes/talent.$freelancerId'
import { Route as FreelancerPortfolioFreelancerIdRouteImport } from './routes/freelancer-portfolio.$freelancerId'
import { Route as DashboardSubscriptionCheckoutRouteImport } from './routes/dashboard/subscription-checkout'
import { Route as DashboardPremiumRouteImport } from './routes/dashboard/premium'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard/messages'
import { Route as DashboardFreelancerRouteImport } from './routes/dashboard/freelancer'
import { Route as DashboardContractsRouteImport } from './routes/dashboard/contracts'
import { Route as DashboardClientRouteImport } from './routes/dashboard/client'
import { Route as DashboardFreelancerServicesRouteImport } from './routes/dashboard/freelancer.services'
import { Route as DashboardFreelancerProjectsRouteImport } from './routes/dashboard/freelancer.projects'
import { Route as DashboardFreelancerProfileRouteImport } from './routes/dashboard/freelancer.profile'
import { Route as DashboardFreelancerPortfolioRouteImport } from './routes/dashboard/freelancer.portfolio'
import { Route as DashboardContractsContractIdRouteImport } from './routes/dashboard/contracts.$contractId'
import { Route as DashboardClientServicesRouteImport } from './routes/dashboard/client.services'
import { Route as DashboardClientSearchRouteImport } from './routes/dashboard/client.search'
import { Route as DashboardClientProjectsRouteImport } from './routes/dashboard/client.projects'
import { Route as DashboardClientProfileRouteImport } from './routes/dashboard/client.profile'
import { Route as DashboardFreelancerProjectsProjectIdRouteImport } from './routes/dashboard/freelancer/projects.$projectId'
import { Route as DashboardFreelancerMypesMypeIdRouteImport } from './routes/dashboard/freelancer/mypes.$mypeId'
import { Route as DashboardClientServicesServiceIdRouteImport } from './routes/dashboard/client.services.$serviceId'
import { Route as DashboardClientFreelancersFreelancerIdRouteImport } from './routes/dashboard/client/freelancers.$freelancerId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const MypeOnboardingRoute = MypeOnboardingRouteImport.update({
  id: '/mype-onboarding',
  path: '/mype-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerOnboardingRoute = FreelancerOnboardingRouteImport.update({
  id: '/freelancer-onboarding',
  path: '/freelancer-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentFreelancerIdRoute = TalentFreelancerIdRouteImport.update({
  id: '/$freelancerId',
  path: '/$freelancerId',
  getParentRoute: () => TalentRoute,
} as any)
const FreelancerPortfolioFreelancerIdRoute =
  FreelancerPortfolioFreelancerIdRouteImport.update({
    id: '/freelancer-portfolio/$freelancerId',
    path: '/freelancer-portfolio/$freelancerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSubscriptionCheckoutRoute =
  DashboardSubscriptionCheckoutRouteImport.update({
    id: '/dashboard/subscription-checkout',
    path: '/dashboard/subscription-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPremiumRoute = DashboardPremiumRouteImport.update({
  id: '/dashboard/premium',
  path: '/dashboard/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/dashboard/payments',
  path: '/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/dashboard/messages',
  path: '/dashboard/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFreelancerRoute = DashboardFreelancerRouteImport.update({
  id: '/dashboard/freelancer',
  path: '/dashboard/freelancer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContractsRoute = DashboardContractsRouteImport.update({
  id: '/dashboard/contracts',
  path: '/dashboard/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientRoute = DashboardClientRouteImport.update({
  id: '/dashboard/client',
  path: '/dashboard/client',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFreelancerServicesRoute =
  DashboardFreelancerServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const DashboardFreelancerProjectsRoute =
  DashboardFreelancerProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const DashboardFreelancerProfileRoute =
  DashboardFreelancerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const DashboardFreelancerPortfolioRoute =
  DashboardFreelancerPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const DashboardContractsContractIdRoute =
  DashboardContractsContractIdRouteImport.update({
    id: '/$contractId',
    path: '/$contractId',
    getParentRoute: () => DashboardContractsRoute,
  } as any)
const DashboardClientServicesRoute = DashboardClientServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardClientRoute,
} as any)
const DashboardClientSearchRoute = DashboardClientSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardClientRoute,
} as any)
const DashboardClientProjectsRoute = DashboardClientProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardClientRoute,
} as any)
const DashboardClientProfileRoute = DashboardClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardClientRoute,
} as any)
const DashboardFreelancerProjectsProjectIdRoute =
  DashboardFreelancerProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardFreelancerProjectsRoute,
  } as any)
const DashboardFreelancerMypesMypeIdRoute =
  DashboardFreelancerMypesMypeIdRouteImport.update({
    id: '/mypes/$mypeId',
    path: '/mypes/$mypeId',
    getParentRoute: () => DashboardFreelancerRoute,
  } as any)
const DashboardClientServicesServiceIdRoute =
  DashboardClientServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => DashboardClientServicesRoute,
  } as any)
const DashboardClientFreelancersFreelancerIdRoute =
  DashboardClientFreelancersFreelancerIdRouteImport.update({
    id: '/freelancers/$freelancerId',
    path: '/freelancers/$freelancerId',
    getParentRoute: () => DashboardClientRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/freelancer-onboarding': typeof FreelancerOnboardingRoute
  '/login': typeof LoginRoute
  '/mype-onboarding': typeof MypeOnboardingRoute
  '/premium': typeof PremiumRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof TalentRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/client': typeof DashboardClientRouteWithChildren
  '/dashboard/contracts': typeof DashboardContractsRouteWithChildren
  '/dashboard/freelancer': typeof DashboardFreelancerRouteWithChildren
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/premium': typeof DashboardPremiumRoute
  '/dashboard/subscription-checkout': typeof DashboardSubscriptionCheckoutRoute
  '/freelancer-portfolio/$freelancerId': typeof FreelancerPortfolioFreelancerIdRoute
  '/talent/$freelancerId': typeof TalentFreelancerIdRoute
  '/dashboard/client/profile': typeof DashboardClientProfileRoute
  '/dashboard/client/projects': typeof DashboardClientProjectsRoute
  '/dashboard/client/search': typeof DashboardClientSearchRoute
  '/dashboard/client/services': typeof DashboardClientServicesRouteWithChildren
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdRoute
  '/dashboard/freelancer/portfolio': typeof DashboardFreelancerPortfolioRoute
  '/dashboard/freelancer/profile': typeof DashboardFreelancerProfileRoute
  '/dashboard/freelancer/projects': typeof DashboardFreelancerProjectsRouteWithChildren
  '/dashboard/freelancer/services': typeof DashboardFreelancerServicesRoute
  '/dashboard/client/freelancers/$freelancerId': typeof DashboardClientFreelancersFreelancerIdRoute
  '/dashboard/client/services/$serviceId': typeof DashboardClientServicesServiceIdRoute
  '/dashboard/freelancer/mypes/$mypeId': typeof DashboardFreelancerMypesMypeIdRoute
  '/dashboard/freelancer/projects/$projectId': typeof DashboardFreelancerProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/freelancer-onboarding': typeof FreelancerOnboardingRoute
  '/login': typeof LoginRoute
  '/mype-onboarding': typeof MypeOnboardingRoute
  '/premium': typeof PremiumRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof TalentRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/client': typeof DashboardClientRouteWithChildren
  '/dashboard/contracts': typeof DashboardContractsRouteWithChildren
  '/dashboard/freelancer': typeof DashboardFreelancerRouteWithChildren
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/premium': typeof DashboardPremiumRoute
  '/dashboard/subscription-checkout': typeof DashboardSubscriptionCheckoutRoute
  '/freelancer-portfolio/$freelancerId': typeof FreelancerPortfolioFreelancerIdRoute
  '/talent/$freelancerId': typeof TalentFreelancerIdRoute
  '/dashboard/client/profile': typeof DashboardClientProfileRoute
  '/dashboard/client/projects': typeof DashboardClientProjectsRoute
  '/dashboard/client/search': typeof DashboardClientSearchRoute
  '/dashboard/client/services': typeof DashboardClientServicesRouteWithChildren
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdRoute
  '/dashboard/freelancer/portfolio': typeof DashboardFreelancerPortfolioRoute
  '/dashboard/freelancer/profile': typeof DashboardFreelancerProfileRoute
  '/dashboard/freelancer/projects': typeof DashboardFreelancerProjectsRouteWithChildren
  '/dashboard/freelancer/services': typeof DashboardFreelancerServicesRoute
  '/dashboard/client/freelancers/$freelancerId': typeof DashboardClientFreelancersFreelancerIdRoute
  '/dashboard/client/services/$serviceId': typeof DashboardClientServicesServiceIdRoute
  '/dashboard/freelancer/mypes/$mypeId': typeof DashboardFreelancerMypesMypeIdRoute
  '/dashboard/freelancer/projects/$projectId': typeof DashboardFreelancerProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/freelancer-onboarding': typeof FreelancerOnboardingRoute
  '/login': typeof LoginRoute
  '/mype-onboarding': typeof MypeOnboardingRoute
  '/premium': typeof PremiumRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof TalentRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/client': typeof DashboardClientRouteWithChildren
  '/dashboard/contracts': typeof DashboardContractsRouteWithChildren
  '/dashboard/freelancer': typeof DashboardFreelancerRouteWithChildren
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/premium': typeof DashboardPremiumRoute
  '/dashboard/subscription-checkout': typeof DashboardSubscriptionCheckoutRoute
  '/freelancer-portfolio/$freelancerId': typeof FreelancerPortfolioFreelancerIdRoute
  '/talent/$freelancerId': typeof TalentFreelancerIdRoute
  '/dashboard/client/profile': typeof DashboardClientProfileRoute
  '/dashboard/client/projects': typeof DashboardClientProjectsRoute
  '/dashboard/client/search': typeof DashboardClientSearchRoute
  '/dashboard/client/services': typeof DashboardClientServicesRouteWithChildren
  '/dashboard/contracts/$contractId': typeof DashboardContractsContractIdRoute
  '/dashboard/freelancer/portfolio': typeof DashboardFreelancerPortfolioRoute
  '/dashboard/freelancer/profile': typeof DashboardFreelancerProfileRoute
  '/dashboard/freelancer/projects': typeof DashboardFreelancerProjectsRouteWithChildren
  '/dashboard/freelancer/services': typeof DashboardFreelancerServicesRoute
  '/dashboard/client/freelancers/$freelancerId': typeof DashboardClientFreelancersFreelancerIdRoute
  '/dashboard/client/services/$serviceId': typeof DashboardClientServicesServiceIdRoute
  '/dashboard/freelancer/mypes/$mypeId': typeof DashboardFreelancerMypesMypeIdRoute
  '/dashboard/freelancer/projects/$projectId': typeof DashboardFreelancerProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/freelancer-onboarding'
    | '/login'
    | '/mype-onboarding'
    | '/premium'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/talent'
    | '/verify-email'
    | '/dashboard/client'
    | '/dashboard/contracts'
    | '/dashboard/freelancer'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/premium'
    | '/dashboard/subscription-checkout'
    | '/freelancer-portfolio/$freelancerId'
    | '/talent/$freelancerId'
    | '/dashboard/client/profile'
    | '/dashboard/client/projects'
    | '/dashboard/client/search'
    | '/dashboard/client/services'
    | '/dashboard/contracts/$contractId'
    | '/dashboard/freelancer/portfolio'
    | '/dashboard/freelancer/profile'
    | '/dashboard/freelancer/projects'
    | '/dashboard/freelancer/services'
    | '/dashboard/client/freelancers/$freelancerId'
    | '/dashboard/client/services/$serviceId'
    | '/dashboard/freelancer/mypes/$mypeId'
    | '/dashboard/freelancer/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/freelancer-onboarding'
    | '/login'
    | '/mype-onboarding'
    | '/premium'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/talent'
    | '/verify-email'
    | '/dashboard/client'
    | '/dashboard/contracts'
    | '/dashboard/freelancer'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/premium'
    | '/dashboard/subscription-checkout'
    | '/freelancer-portfolio/$freelancerId'
    | '/talent/$freelancerId'
    | '/dashboard/client/profile'
    | '/dashboard/client/projects'
    | '/dashboard/client/search'
    | '/dashboard/client/services'
    | '/dashboard/contracts/$contractId'
    | '/dashboard/freelancer/portfolio'
    | '/dashboard/freelancer/profile'
    | '/dashboard/freelancer/projects'
    | '/dashboard/freelancer/services'
    | '/dashboard/client/freelancers/$freelancerId'
    | '/dashboard/client/services/$serviceId'
    | '/dashboard/freelancer/mypes/$mypeId'
    | '/dashboard/freelancer/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/forgot'
    | '/freelancer-onboarding'
    | '/login'
    | '/mype-onboarding'
    | '/premium'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/talent'
    | '/verify-email'
    | '/dashboard/client'
    | '/dashboard/contracts'
    | '/dashboard/freelancer'
    | '/dashboard/messages'
    | '/dashboard/payments'
    | '/dashboard/premium'
    | '/dashboard/subscription-checkout'
    | '/freelancer-portfolio/$freelancerId'
    | '/talent/$freelancerId'
    | '/dashboard/client/profile'
    | '/dashboard/client/projects'
    | '/dashboard/client/search'
    | '/dashboard/client/services'
    | '/dashboard/contracts/$contractId'
    | '/dashboard/freelancer/portfolio'
    | '/dashboard/freelancer/profile'
    | '/dashboard/freelancer/projects'
    | '/dashboard/freelancer/services'
    | '/dashboard/client/freelancers/$freelancerId'
    | '/dashboard/client/services/$serviceId'
    | '/dashboard/freelancer/mypes/$mypeId'
    | '/dashboard/freelancer/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotRoute: typeof ForgotRoute
  FreelancerOnboardingRoute: typeof FreelancerOnboardingRoute
  LoginRoute: typeof LoginRoute
  MypeOnboardingRoute: typeof MypeOnboardingRoute
  PremiumRoute: typeof PremiumRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TalentRoute: typeof TalentRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  DashboardClientRoute: typeof DashboardClientRouteWithChildren
  DashboardContractsRoute: typeof DashboardContractsRouteWithChildren
  DashboardFreelancerRoute: typeof DashboardFreelancerRouteWithChildren
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardPremiumRoute: typeof DashboardPremiumRoute
  DashboardSubscriptionCheckoutRoute: typeof DashboardSubscriptionCheckoutRoute
  FreelancerPortfolioFreelancerIdRoute: typeof FreelancerPortfolioFreelancerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mype-onboarding': {
      id: '/mype-onboarding'
      path: '/mype-onboarding'
      fullPath: '/mype-onboarding'
      preLoaderRoute: typeof MypeOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer-onboarding': {
      id: '/freelancer-onboarding'
      path: '/freelancer-onboarding'
      fullPath: '/freelancer-onboarding'
      preLoaderRoute: typeof FreelancerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$freelancerId': {
      id: '/talent/$freelancerId'
      path: '/$freelancerId'
      fullPath: '/talent/$freelancerId'
      preLoaderRoute: typeof TalentFreelancerIdRouteImport
      parentRoute: typeof TalentRoute
    }
    '/freelancer-portfolio/$freelancerId': {
      id: '/freelancer-portfolio/$freelancerId'
      path: '/freelancer-portfolio/$freelancerId'
      fullPath: '/freelancer-portfolio/$freelancerId'
      preLoaderRoute: typeof FreelancerPortfolioFreelancerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subscription-checkout': {
      id: '/dashboard/subscription-checkout'
      path: '/dashboard/subscription-checkout'
      fullPath: '/dashboard/subscription-checkout'
      preLoaderRoute: typeof DashboardSubscriptionCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/premium': {
      id: '/dashboard/premium'
      path: '/dashboard/premium'
      fullPath: '/dashboard/premium'
      preLoaderRoute: typeof DashboardPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/freelancer': {
      id: '/dashboard/freelancer'
      path: '/dashboard/freelancer'
      fullPath: '/dashboard/freelancer'
      preLoaderRoute: typeof DashboardFreelancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contracts': {
      id: '/dashboard/contracts'
      path: '/dashboard/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/client': {
      id: '/dashboard/client'
      path: '/dashboard/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof DashboardClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/freelancer/services': {
      id: '/dashboard/freelancer/services'
      path: '/services'
      fullPath: '/dashboard/freelancer/services'
      preLoaderRoute: typeof DashboardFreelancerServicesRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/dashboard/freelancer/projects': {
      id: '/dashboard/freelancer/projects'
      path: '/projects'
      fullPath: '/dashboard/freelancer/projects'
      preLoaderRoute: typeof DashboardFreelancerProjectsRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/dashboard/freelancer/profile': {
      id: '/dashboard/freelancer/profile'
      path: '/profile'
      fullPath: '/dashboard/freelancer/profile'
      preLoaderRoute: typeof DashboardFreelancerProfileRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/dashboard/freelancer/portfolio': {
      id: '/dashboard/freelancer/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/freelancer/portfolio'
      preLoaderRoute: typeof DashboardFreelancerPortfolioRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/dashboard/contracts/$contractId': {
      id: '/dashboard/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/dashboard/contracts/$contractId'
      preLoaderRoute: typeof DashboardContractsContractIdRouteImport
      parentRoute: typeof DashboardContractsRoute
    }
    '/dashboard/client/services': {
      id: '/dashboard/client/services'
      path: '/services'
      fullPath: '/dashboard/client/services'
      preLoaderRoute: typeof DashboardClientServicesRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/client/search': {
      id: '/dashboard/client/search'
      path: '/search'
      fullPath: '/dashboard/client/search'
      preLoaderRoute: typeof DashboardClientSearchRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/client/projects': {
      id: '/dashboard/client/projects'
      path: '/projects'
      fullPath: '/dashboard/client/projects'
      preLoaderRoute: typeof DashboardClientProjectsRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/client/profile': {
      id: '/dashboard/client/profile'
      path: '/profile'
      fullPath: '/dashboard/client/profile'
      preLoaderRoute: typeof DashboardClientProfileRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/freelancer/projects/$projectId': {
      id: '/dashboard/freelancer/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/freelancer/projects/$projectId'
      preLoaderRoute: typeof DashboardFreelancerProjectsProjectIdRouteImport
      parentRoute: typeof DashboardFreelancerProjectsRoute
    }
    '/dashboard/freelancer/mypes/$mypeId': {
      id: '/dashboard/freelancer/mypes/$mypeId'
      path: '/mypes/$mypeId'
      fullPath: '/dashboard/freelancer/mypes/$mypeId'
      preLoaderRoute: typeof DashboardFreelancerMypesMypeIdRouteImport
      parentRoute: typeof DashboardFreelancerRoute
    }
    '/dashboard/client/services/$serviceId': {
      id: '/dashboard/client/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/dashboard/client/services/$serviceId'
      preLoaderRoute: typeof DashboardClientServicesServiceIdRouteImport
      parentRoute: typeof DashboardClientServicesRoute
    }
    '/dashboard/client/freelancers/$freelancerId': {
      id: '/dashboard/client/freelancers/$freelancerId'
      path: '/freelancers/$freelancerId'
      fullPath: '/dashboard/client/freelancers/$freelancerId'
      preLoaderRoute: typeof DashboardClientFreelancersFreelancerIdRouteImport
      parentRoute: typeof DashboardClientRoute
    }
  }
}

interface TalentRouteChildren {
  TalentFreelancerIdRoute: typeof TalentFreelancerIdRoute
}

const TalentRouteChildren: TalentRouteChildren = {
  TalentFreelancerIdRoute: TalentFreelancerIdRoute,
}

const TalentRouteWithChildren =
  TalentRoute._addFileChildren(TalentRouteChildren)

interface DashboardClientServicesRouteChildren {
  DashboardClientServicesServiceIdRoute: typeof DashboardClientServicesServiceIdRoute
}

const DashboardClientServicesRouteChildren: DashboardClientServicesRouteChildren =
  {
    DashboardClientServicesServiceIdRoute:
      DashboardClientServicesServiceIdRoute,
  }

const DashboardClientServicesRouteWithChildren =
  DashboardClientServicesRoute._addFileChildren(
    DashboardClientServicesRouteChildren,
  )

interface DashboardClientRouteChildren {
  DashboardClientProfileRoute: typeof DashboardClientProfileRoute
  DashboardClientProjectsRoute: typeof DashboardClientProjectsRoute
  DashboardClientSearchRoute: typeof DashboardClientSearchRoute
  DashboardClientServicesRoute: typeof DashboardClientServicesRouteWithChildren
  DashboardClientFreelancersFreelancerIdRoute: typeof DashboardClientFreelancersFreelancerIdRoute
}

const DashboardClientRouteChildren: DashboardClientRouteChildren = {
  DashboardClientProfileRoute: DashboardClientProfileRoute,
  DashboardClientProjectsRoute: DashboardClientProjectsRoute,
  DashboardClientSearchRoute: DashboardClientSearchRoute,
  DashboardClientServicesRoute: DashboardClientServicesRouteWithChildren,
  DashboardClientFreelancersFreelancerIdRoute:
    DashboardClientFreelancersFreelancerIdRoute,
}

const DashboardClientRouteWithChildren = DashboardClientRoute._addFileChildren(
  DashboardClientRouteChildren,
)

interface DashboardContractsRouteChildren {
  DashboardContractsContractIdRoute: typeof DashboardContractsContractIdRoute
}

const DashboardContractsRouteChildren: DashboardContractsRouteChildren = {
  DashboardContractsContractIdRoute: DashboardContractsContractIdRoute,
}

const DashboardContractsRouteWithChildren =
  DashboardContractsRoute._addFileChildren(DashboardContractsRouteChildren)

interface DashboardFreelancerProjectsRouteChildren {
  DashboardFreelancerProjectsProjectIdRoute: typeof DashboardFreelancerProjectsProjectIdRoute
}

const DashboardFreelancerProjectsRouteChildren: DashboardFreelancerProjectsRouteChildren =
  {
    DashboardFreelancerProjectsProjectIdRoute:
      DashboardFreelancerProjectsProjectIdRoute,
  }

const DashboardFreelancerProjectsRouteWithChildren =
  DashboardFreelancerProjectsRoute._addFileChildren(
    DashboardFreelancerProjectsRouteChildren,
  )

interface DashboardFreelancerRouteChildren {
  DashboardFreelancerPortfolioRoute: typeof DashboardFreelancerPortfolioRoute
  DashboardFreelancerProfileRoute: typeof DashboardFreelancerProfileRoute
  DashboardFreelancerProjectsRoute: typeof DashboardFreelancerProjectsRouteWithChildren
  DashboardFreelancerServicesRoute: typeof DashboardFreelancerServicesRoute
  DashboardFreelancerMypesMypeIdRoute: typeof DashboardFreelancerMypesMypeIdRoute
}

const DashboardFreelancerRouteChildren: DashboardFreelancerRouteChildren = {
  DashboardFreelancerPortfolioRoute: DashboardFreelancerPortfolioRoute,
  DashboardFreelancerProfileRoute: DashboardFreelancerProfileRoute,
  DashboardFreelancerProjectsRoute:
    DashboardFreelancerProjectsRouteWithChildren,
  DashboardFreelancerServicesRoute: DashboardFreelancerServicesRoute,
  DashboardFreelancerMypesMypeIdRoute: DashboardFreelancerMypesMypeIdRoute,
}

const DashboardFreelancerRouteWithChildren =
  DashboardFreelancerRoute._addFileChildren(DashboardFreelancerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotRoute: ForgotRoute,
  FreelancerOnboardingRoute: FreelancerOnboardingRoute,
  LoginRoute: LoginRoute,
  MypeOnboardingRoute: MypeOnboardingRoute,
  PremiumRoute: PremiumRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TalentRoute: TalentRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  DashboardClientRoute: DashboardClientRouteWithChildren,
  DashboardContractsRoute: DashboardContractsRouteWithChildren,
  DashboardFreelancerRoute: DashboardFreelancerRouteWithChildren,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardPremiumRoute: DashboardPremiumRoute,
  DashboardSubscriptionCheckoutRoute: DashboardSubscriptionCheckoutRoute,
  FreelancerPortfolioFreelancerIdRoute: FreelancerPortfolioFreelancerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
